service: hello-world-step-fn

configValidationMode: error

package:
  include:
    - src/

custom:
  esbuild:
    bundle: true
    minify: true
    target: node12
  localstack:
    debug: true
    autostart: false
    stages:
      - dev
    host: http://localstack
    edgePort: 4566
    lambda:
      mountCode: false

plugins:
  - serverless-esbuild
  - serverless-localstack
  - serverless-step-functions

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-southeast-2'}
  memorySize: 192 #mb (default for all)
  iamRoleStatements: []

functions:
  hello:
    handler: src/hello.handler
  world:
    handler: src/world.handler

stepFunctions:
  stateMachines:
    helloWorld:
      name: helloWorld
      definition:
        StartAt: Hello
        States:
          Hello:
            Type: Task
            Resource: 
              Fn::GetAtt: [hello, Arn]
            Next: World
          World:
            Type: Task
            Resource: 
              Fn::GetAtt: [world, Arn]
            Next: Passthru
          Passthru:
            Type: Pass
            Next: Stop
          Stop:
            Type: Pass
            End: true